/**
 * Public origins of the services, on Lagoon and elsewhere.
 *
 * Lagoon injects `LAGOON_ROUTES` (every route of the environment, comma
 * separated) and `LAGOON_ROUTE` (the main one) into each container. Its
 * autogenerated hostnames start with the service name — `cms.<project>-<env>…`,
 * `web.<project>-<env>…` — which is how a fresh environment finds its own URLs
 * with no variable to set. Custom domains break that convention, so an explicit
 * variable always wins, and with exactly two routes the one that is not the site
 * is taken to be the CMS.
 */
const stripSlash = (url: string) => url.replace(/\/+$/, '')

export function lagoonRoutes(): string[] {
  return (process.env.LAGOON_ROUTES ?? '')
    .split(',')
    .map((route) => route.trim())
    .filter(Boolean)
    .map(stripSlash)
}

function routeForService(service: string): string | undefined {
  const pattern = new RegExp(`^https?://${service}\\.`)
  return lagoonRoutes().find((route) => pattern.test(route))
}

/** Origin of the Astro site — the live preview target and the CORS/CSRF peer. */
export function resolveSiteURL(): string | undefined {
  const explicit = process.env.PREVIEW_URL ?? process.env.SITE_URL
  if (explicit) return stripSlash(explicit)
  const main = process.env.LAGOON_ROUTE ? stripSlash(process.env.LAGOON_ROUTE) : undefined
  return routeForService('web') ?? main
}

/** Origin of this CMS. */
export function resolveCmsURL(): string | undefined {
  const explicit = process.env.NEXT_PUBLIC_SERVER_URL
  if (explicit) return stripSlash(explicit)
  const prefixed = routeForService('cms')
  if (prefixed) return prefixed
  const routes = lagoonRoutes()
  const site = resolveSiteURL()
  return routes.length === 2 ? routes.find((route) => route !== site) : undefined
}
