// Must stay first: populates process.env before anything else reads it.
import './lib/env'

import { PayloadAiPluginLexicalEditorFeature } from '@ai-stack/payloadcms'
import { postgresAdapter } from '@payloadcms/db-postgres'
import { BlocksFeature, CodeBlock, lexicalEditor } from '@payloadcms/richtext-lexical'
import path from 'path'
import { buildConfig } from 'payload'
import { fileURLToPath } from 'url'
import sharp from 'sharp'

import { Categories } from './collections/Categories'
import { Docs } from './collections/Docs'
import { Media } from './collections/Media'
import { Users } from './collections/Users'
import { amazeeAiEnabled, amazeeAiPlugin } from './ai/amazeeAi'
import { resolveDatabaseUri } from './lib/databaseUri'
import { resolveCmsURL, resolveSiteURL } from './lib/lagoonRoutes'
import { migrations } from './migrations'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)

const CODE_LANGUAGES = {
  bash: 'Bash',
  json: 'JSON',
  yaml: 'YAML',
  typescript: 'TypeScript',
  javascript: 'JavaScript',
  tsx: 'TSX',
  astro: 'Astro',
  graphql: 'GraphQL',
  dockerfile: 'Dockerfile',
  nginx: 'nginx',
  sql: 'SQL',
  html: 'HTML',
  css: 'CSS',
  markdown: 'Markdown',
  diff: 'Diff',
  plaintext: 'Plain text',
}

/**
 * Public URL of this CMS. Payload appends it to the CSRF allowlist on its own
 * (`sanitizeConfig`), and without it the admin panel cannot write: browsers send
 * an `Origin` header on same-origin POSTs, `extractJWT` finds it missing from a
 * non-empty `csrf` list and drops the session cookie, so every save comes back
 * as "You are not allowed to perform this action."
 *
 * On Lagoon it is read off the environment's routes (see lib/lagoonRoutes.ts);
 * `NEXT_PUBLIC_SERVER_URL` overrides that. The localhost fallback only holds in
 * development. In production a wrong value reproduces that exact bug against
 * the real domain, so an unresolved origin stops the boot instead of shipping an
 * admin panel that cannot save — except while `next build` collects page data
 * inside the image build, where no route exists yet and nothing is served.
 */
function resolveServerURL(): string {
  const resolved = resolveCmsURL()
  if (resolved) return resolved

  const building = process.env.NEXT_PHASE === 'phase-production-build'
  if (process.env.NODE_ENV === 'production' && !building) {
    throw new Error(
      'Public URL of the CMS unknown: set NEXT_PUBLIC_SERVER_URL, or run on Lagoon ' +
        'with an autogenerated `cms.` route. Without it the admin panel rejects its own ' +
        'writes on CSRF grounds.',
    )
  }

  return 'http://localhost:3000'
}

const serverURL = resolveServerURL()

/**
 * Origin of the Astro site serving `/preview/*`. It is the parent of the
 * postMessage exchange, so it also has to be a CORS and CSRF origin: the
 * live-preview SDK POSTs the unsaved document back to this API with
 * `credentials: 'include'`, and a missing entry makes that call fail silently.
 */
const previewURL = resolveSiteURL() ?? 'http://localhost:4321'

/** Shared secret guarding the preview route — see apps/web/src/site.ts. */
const previewSecret = process.env.PREVIEW_SECRET ?? ''

/** Origins allowed to query the API: the Astro site, in dev and in production. */
const allowedOrigins = [...new Set([previewURL, 'http://localhost:4321'])]

export default buildConfig({
  serverURL,
  admin: {
    user: Users.slug,
    importMap: {
      baseDir: path.resolve(dirname),
    },
    // The admin panel embeds the Astro site in an iframe and pushes the unsaved
    // form state to it over postMessage; `/preview/*` renders it on demand.
    livePreview: {
      collections: ['docs'],
      // Recomputed on every keystroke once autosave is on — keep it cheap and
      // synchronous.
      url: ({ data, locale }) => {
        const slug = typeof data?.slug === 'string' ? data.slug : null
        // A document that has never been saved has no slug: returning null
        // leaves the panel empty instead of pointing the iframe at a 404.
        if (!slug) return null
        return `${previewURL}/preview/${locale?.code ?? 'en'}/${slug}?secret=${previewSecret}`
      },
      breakpoints: [
        { name: 'mobile', label: 'Mobile', width: 375, height: 667 },
        { name: 'tablet', label: 'Tablet', width: 768, height: 1024 },
      ],
    },
  },
  collections: [Docs, Categories, Media, Users],
  // Must stay in sync with LOCALES in apps/web/src/site.ts.
  localization: {
    locales: ['en', 'fr'],
    defaultLocale: 'en',
    fallback: true,
  },
  cors: allowedOrigins,
  csrf: allowedOrigins,
  // The Lexical editor has no built-in code block — a dealbreaker for technical
  // documentation. `CodeBlock` is the block Payload ships: it brings the editing
  // UI and, more importantly, a two-way Markdown converter that preserves ```
  // fences and their language in both directions.
  //
  // Its default list is Monaco's (about a hundred entries, and `shell` rather
  // than `bash`). We narrow it to what this project actually uses, with
  // identifiers Shiki recognises on the Astro side: the value picked here lands
  // verbatim after the ``` and drives syntax highlighting.
  //
  // The AI feature adds the assistant menu (compose, proofread, translate,
  // rephrase) to every rich text field. It is only registered together with the
  // plugin: without a gateway token the menu would render but every action fail.
  editor: lexicalEditor({
    features: ({ defaultFeatures }) => [
      ...defaultFeatures,
      BlocksFeature({ blocks: [CodeBlock({ languages: CODE_LANGUAGES })] }),
      ...(amazeeAiEnabled ? [PayloadAiPluginLexicalEditorFeature()] : []),
    ],
  }),
  secret: process.env.PAYLOAD_SECRET || '',
  typescript: {
    outputFile: path.resolve(dirname, 'payload-types.ts'),
  },
  db: postgresAdapter({
    pool: { connectionString: resolveDatabaseUri() },
    // Development pushes the schema on the fly. Production has no such thing:
    // the migrations under src/migrations run when Payload initialises — in the
    // server as well as in the seed, whichever starts first.
    prodMigrations: migrations,
  }),
  sharp,
  // See apps/cms/src/ai/amazeeAi.ts — a no-op without AMAZEE_AI_API_TOKEN.
  plugins: amazeeAiEnabled ? [amazeeAiPlugin()] : [],
})
